name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller requests PyQt5 zeroconf pillow reportlab

    - name: Clean previous builds
      run: |
        Remove-Item -Recurse -Force build, dist, Main.spec -ErrorAction SilentlyContinue

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed \
          --hidden-import requests \
          --hidden-import zeroconf \
          --hidden-import zeroconf._utils.ipaddress \
          --hidden-import zeroconf._core \
          --hidden-import zeroconf._engine \
          --hidden-import zeroconf._services.info \
          --hidden-import pillow \
          --hidden-import reportlab \
          --collect-all PyQt5 \
          --collect-all zeroconf \
          Main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ScannerPrinter
        path: dist/Main.exe
